Fixed security issue on league/flysystem.
oat-sa/qti-sdk pull request #290
Opened 2021-07-06 12:32 UTC by julien-sebire

This PR fixes a security issue found in league/flysystem dependency.
See https://github.com/oat-sa/qti-sdk/security/dependabot/composer.json/league%2Fflysystem/open for more information.

2021-07-07 10:33 UTC, wazelin requested changes

2021-07-07 10:33 UTC, wazelin commented on composer.json
> +		"league/flysystem": ">=1.1.4 <2.0.0",
A more clean and concise equivalent would be the following.

```suggestion
		"league/flysystem": "^1.1.4",
```

2021-07-13 07:24 UTC, augustas approved these changes

2022-08-24 06:39 UTC, julien-sebire commented
This is not needed any more because the fix is applied with the current constraint.

2022-08-24 06:39 UTC, closed without merging