fix: Record container handle list when unmarshalling
oat-sa/qti-sdk pull request #339
Opened 2022-10-25 10:15 UTC by bartlomiejmarszal

When unmarshalling RecordContainer list can be handle

2022-10-25 11:24 UTC, bugalot requested changes
Unfortunately, the Unit Tests return the following issue:

```
1) qtismtest\runtime\pci\json\JsonUnmarshallerTest::testUnmarshallRecord with data set #4 (qtism\runtime\common\RecordContainer Object (...), '{ "record" : [ {"name": "A","... } ] }')
Failed asserting that false is true.
```

2022-10-26 11:04 UTC, bugalot approved these changes

2022-10-26 12:16 UTC, pnal approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits]
- [x] Commits messages are meaningful
- [x] Commits are atomic

2022-10-27 16:31 UTC, julien-sebire approved these changes

2022-10-27 16:32 UTC, julien-sebire commented
Please don't forget to do the same change on main branch to avoid increasing gaps.

2022-11-02 15:57 UTC, merged