NOT FINAL: Specify return types
oat-sa/qti-sdk pull request #346
Opened 2022-11-16 15:52 UTC by kilatib

# [TR-4876](https://oat-sa.atlassian.net/browse/TR-4876)

## Description 
[PHP 8.1: Return types in PHP built-in class methods and deprecation notices](https://php.watch/versions/8.1/internal-method-return-types)

[oat-sa/qti-sdk](https://github.com/oat-sa/qti-sdk) extends SPL objects heavily without specifying any return types, and that is also considered a return type mismatch starting from PHP 8.1, e.g. [qti-sdk/QtiIdentifiableCollection.php at 5d14c9f5f046656c3d0396535f0447dd83ee9478 · oat-sa/qti-sdk](https://github.com/oat-sa/qti-sdk/blob/5d14c9f5f046656c3d0396535f0447dd83ee9478/src/qtism/data/QtiIdentifiableCollection.php#L144)

## Solution 
Introduce a nominal breaking change by specifying return types of all the built-in-class-extending methods

## Development impact 
provide return type to methods 

@wazelin @poyuki  here I provided changes for with type: `mixed` and union types it makes this lib support only php 8 should I?

2022-11-16 15:52 UTC, kilatib commented
@wazelin @poyuki  here I provided changes for with type: `mixed` and union types it makes this lib support only php 8 should I?  
Not to much changes I did should it be more specific ?

2022-11-21 14:57 UTC, poyuki commented on src/qtism/common/beans/Bean.php
> +     * A setter is considered to be valid if:.
after this statement follow list of cases when setter considered as valid so i guess point not applicable here

2022-11-22 18:25 UTC, poyuki requested changes
That was huge one. Great job! I guess most of changes provided by some code styler, but some of those changes require manual adjustment. Also for me not clear some points with return types and `ReturnTypeWillChange` attribute usage. Didn't check every thing for a moment. will continue tomorrow.

2022-11-22 18:25 UTC, poyuki commented on src/qtism/data/content/interactions/GapChoice.php
> + * From IMS QTI:.
```suggestion
 * From IMS QTI:
```

2022-11-22 18:25 UTC, poyuki commented on src/qtism/data/content/interactions/GapMatchInteraction.php
> + * From IMS QTI:.
```suggestion
 * From IMS QTI:
```

2022-11-22 18:25 UTC, poyuki commented on src/qtism/data/content/interactions/GraphicAssociateInteraction.php
>      public function __construct($responseIdentifier, ObjectElement $object, AssociableHotspotCollection $associableHotspots, $id = '', $class = '', $lang = '', $label = '')
```suggestion
    public function __construct(
        $responseIdentifier,
        ObjectElement $object,
        AssociableHotspotCollection $associableHotspots,
        $id = '',
        $class = '',
        $lang = '',
        $label = ''
    ) {
```

2022-11-22 18:25 UTC, poyuki commented on src/qtism/data/content/interactions/InlineChoiceInteraction.php
> + * From IMS QTI:.
```suggestion
 * From IMS QTI:
```

2022-11-22 18:25 UTC, poyuki commented on test/qtismtest/runtime/expressions/operators/custom/org/qtism/test/Explode.php
>      public function process()
```suggestion
     */
    #[\ReturnTypeWillChange]
    public function process()
```

2022-11-23 09:45 UTC, kilatib commented on src/qtism/common/enums/Enumeration.php
>      public static function getConstantByName($name);
good catch

2022-11-23 13:19 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/Marshaller.php
> +                ) !== '' && $element->localName !== $this->getExpectedQtiClassName())) {
could you provide here proper multiline if statement as suggested earlier or revert that place

2022-11-23 13:20 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/MarshallerFactory.php
> +                )) {
could you provide here proper multiline if statement as suggested earlier or revert that place

2022-11-23 13:20 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/MarshallerFactory.php
> +                    )) {
could you provide here proper multiline if statement as suggested earlier or revert that place

2022-11-23 13:21 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/MatchInteractionMarshaller.php
> +                    ) . "' given.";
could you convert it in `sprintf` or revert?

2022-11-23 13:21 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/MatchInteractionMarshaller.php
> +                )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place

2022-11-23 13:21 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/MatchInteractionMarshaller.php
> +                ) !== false) || Version::compare($version, '2.1.0', '<') === true) {
could you provide here proper multiline if statement as suggested earlier or revert that place

2022-11-23 13:23 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/MathMarshaller.php
> +    #[\ReturnTypeWillChange]
does it realy necesary?

2022-11-23 13:24 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/NullValueMarshaller.php
> +    #[\ReturnTypeWillChange]
does it really necesary?

2022-11-23 13:24 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/NumberCorrectMarshaller.php
> +    #[\ReturnTypeWillChange]
the same

2022-11-23 13:27 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/OutcomeControlMarshaller.php
> +            ) == 0) {
could you provide here proper multiline if statement as suggested earlier or revert that place

2022-11-23 13:27 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/OutcomeControlMarshaller.php
> +                ) . "'.";
could you convert it in `sprintf` or revert?

2022-11-23 13:28 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/OutcomeDeclarationMarshaller.php
> +                View::asArray()
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:28 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/OutcomeDeclarationMarshaller.php
> +                )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place

2022-11-23 13:28 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/OutcomeDeclarationMarshaller.php
> +                )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place

2022-11-23 13:28 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/OutcomeDeclarationMarshaller.php
> +                )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place

2022-11-23 13:29 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/PositionObjectInteractionMarshaller.php
> +                    )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place

2022-11-23 13:30 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/PositionObjectStageMarshaller.php
> +                    )->unmarshall($interactionElt);
```suggestion
                    $positionObjectInteractions[] = $this->getMarshallerFactory()
                        ->createMarshaller($interactionElt)
                        ->unmarshall($interactionElt);
```

2022-11-23 13:31 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/PrintedVariableMarshaller.php
> +                )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:31 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/PrintedVariableMarshaller.php
> +                )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:31 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/PrintedVariableMarshaller.php
> +                )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:31 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/PromptMarshaller.php
> +
```suggestion
```

2022-11-23 13:34 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/ResponseControlMarshaller.php
> +            ) == 0) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:34 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/ResponseControlMarshaller.php
> +                ) . "'.";
could you convert it in `sprintf` or revert?

2022-11-23 13:35 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/ResponseDeclarationMarshaller.php
> +            );
```suggestion
            $marshaller = $this->getMarshallerFactory()->createMarshaller(
                $component->getCorrectResponse(),
                [$baseType]
            );
```

2022-11-23 13:38 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/RubricBlockMarshaller.php
> +                    )) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:39 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/SelectionMarshaller.php
> +                )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:40 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/SimpleAssociableChoiceMarshaller.php
> +                    )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:40 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/SimpleAssociableChoiceMarshaller.php
> +                    )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:41 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/SimpleAssociableChoiceMarshaller.php
> +                    )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:41 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/SimpleAssociableChoiceMarshaller.php
> +                    )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:41 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/SimpleChoiceMarshaller.php
> +                )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:41 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/SimpleChoiceMarshaller.php
> +                )) !== null) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:43 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/TemplateControlMarshaller.php
> +            ) == 0) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:43 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/TemplateControlMarshaller.php
> +                ) . "'.";
could you convert it in `sprintf` or revert?

2022-11-23 13:45 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/TemplateElementMarshaller.php
> +                                    ) . "' elements.";
could you convert it in `sprintf` or revert?

2022-11-23 13:45 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/TemplateElementMarshaller.php
> +                                    ))) {
could you provide here proper multiline if statement as suggested earlier or revert that place?

2022-11-23 13:45 UTC, poyuki commented on src/qtism/data/storage/xml/marshalling/TemplateElementMarshaller.php
> +                        ) : new FlowStaticCollection();
```suggestion
                        $content = $element->localName === 'templateInline'
                            ? new InlineStaticCollection()
                            : new FlowStaticCollection();
```

2022-11-23 13:55 UTC, poyuki requested changes
One more small batch of comments. I checked 2/3 entire PR.
in common most of them still related to changes provided by some code fix and most of them decreased readability of code. 
I have some doubts about providing strict types and some mismatching of phpdoc block with provided return types, cause it looks like breaking changes and require bump major version.
Also some methods marked by attribute #[ReturnTypeWillChange] actually return the same type of object as mentioned in declared return type, so i didn't understand reasons of that mark.
Also there is one critical place where return type declared but doesn't return anything.

IMO the simplest way to validate this pr will be rollback all this code style related changes and manually adjust only return types

Will continue after some break

2022-11-23 14:41 UTC, kilatib commented
@poyuki, unfortunately it first what I try, but it will not work

2022-11-25 14:21 UTC, julien-sebire requested changes
Mybe to make the PR a bit less huge, it would be nice to split it in at least 2, by keeping all the code formatting in a separate one and only the change that could have an impact (types, const visibility, ...)

2022-11-25 14:21 UTC, julien-sebire commented on src/qtism/data/content/enums/AriaLive.php
> +
The break after the return is unnecessary anyway.

2022-11-29 09:19 UTC, poyuki reviewed
i pushed few commits with adjusting affected place related to multiline if statements and some strings building.
I left some new comments, and also duplicate previous questions which was not addressed anyhow for some reasons

2022-11-29 15:48 UTC, julien-sebire commented
I'm not sure what you're trying to achieve, tbh. The PR should be as small as possible (atomic?), meaning that it should contain only changes about return types. Here you're changing a lot of code formatting (multiline vs unique line, sprintf, ...) This adds complexity to the PR. It's ok to do that, but in another PR that is trivial and doesn't contain any code change.

2022-11-29 15:53 UTC, poyuki commented
@julien-sebire agree with that, but in case as we have those long lines affected but not properly i'd prefer to adjust it to not decrease readability of this library, but ideally rollback those affected lines, and left just return type on step of commit creation would be preferable.

2022-11-30 10:07 UTC, kilatib commented
@julien-sebire and @poyuki 
revert everything left only return type let's concentrate only on it and not pay attention to a long string and others

2022-11-30 17:09 UTC, poyuki reviewed
Looks a way better, thank you. I validated third of it and left a few comments, not critical i guess
Will continue tomorrow, but in common i guess we can rely on tests coverage and apply this changes in some TR TAE (if it works) for QA verification

Good Job!

2022-11-30 18:14 UTC, kilatib commented on src/qtism/common/storage/BinaryStreamAccess.php
> +        return -1;
the method expects a response so it should be provided -1 it is false

2022-12-04 08:47 UTC, poyuki approved these changes
Great job, i left some questions, most of them identical related to cases when attribute and return type declaration provided, please address them but definitely they are not a blockers.
From my point of view we can move forward with this PR

2022-12-04 08:47 UTC, poyuki commented on test/qtismtest/data/storage/xml/marshalling/Html5RtMarshallerTest.php
> +    public const SUBJECT_QTI_CLASS_NAME = 'rt';
i guess such constants in tests can be private

2022-12-04 20:57 UTC, kilatib commented on src/qtism/data/storage/xml/marshalling/AreaMapEntryMarshaller.php
> +    protected function unmarshall(DOMElement $element): AreaMapEntry
Unfortunatly yes because it extends `qtism\data\storage\xml\marshalling\Marshaller` which returns `QtiComponent`

2022-12-04 20:58 UTC, kilatib commented on src/qtism/data/storage/xml/marshalling/AssessmentItemMarshaller.php
> +    protected function unmarshall(DOMElement $element, AssessmentItem $assessmentItem = null): AssessmentItem
Unfortunately yes because it extends `qtism\data\storage\xml\marshalling\Marshaller` which returns `QtiComponent`

2022-12-04 20:59 UTC, kilatib commented on src/qtism/data/storage/xml/marshalling/WeightMarshaller.php
> +    protected function unmarshall(DOMElement $element): Weight
Unfortunately yes because it extends `qtism\data\storage\xml\marshalling\Marshaller` which returns `QtiComponent`

2022-12-04 20:59 UTC, kilatib commented on src/qtism/data/storage/xml/marshalling/XIncludeMarshaller.php
> +    protected function unmarshall(DOMElement $element): XInclude
Unfortunately yes because it extends `qtism\data\storage\xml\marshalling\Marshaller` which returns `QtiComponent`

2022-12-04 21:00 UTC, kilatib commented on test/qtismtest/common/beans/mocks/StrictBean.php
>          return $this->lastName;
it validated here: `qtismtest\common\beans\BeanTest`

2022-12-12 17:04 UTC, wazelin commented on src/qtism/runtime/common/State.php
> +    #[\ReturnTypeWillChange]
Why not just the return type here?
If that breaks test cases on deliver be, it's the test cases that should be adjusted instead.

2022-12-12 19:50 UTC, wazelin commented on src/qtism/data/expressions/RandomInteger.php
> +    #[\ReturnTypeWillChange]
Made this a little more obvious by extending the return type doc.

2022-12-12 19:51 UTC, wazelin commented on src/qtism/runtime/common/State.php
> +    #[\ReturnTypeWillChange]
Attempted to resolve that [here](https://github.com/oat-sa/qti-sdk/pull/346/files/d2585cd856ee70afe05e394fdff4819ca8f39e9a..81869543691aa149285d7c50f90acdf74b273594).

2022-12-23 14:37 UTC, merged