fix: AssessmentItem::setIdentifier uses isNormalizedString
oat-sa/qti-sdk pull request #402
Opened 2024-07-11 14:23 UTC by bartlomiejmarszal

This allow to set identifier that is validated against normalized string

2024-07-11 14:44 UTC, bugalot requested changes
Unit tests required including a sample that was failing before required ;)

2024-07-11 14:45 UTC, bugalot commented
We would like to also see the backport coming, otherwise we will for sure forget. I would strongly suggest to merge this in `develop`, and simply release in order not to miss this in next release.

2024-07-11 14:48 UTC, bugalot commented
OK, now I understand, it's the fix on the legacy version. However, please update the unit tests as well, so that it goes along that version too.

2024-07-12 07:22 UTC, tikhanovichA approved these changes

2024-07-12 11:13 UTC, merged